import { Component, Injectable, Output, OnInit, EventEmitter, Input } from '@angular/core';
import { FormControl, FormGroup, UntypedFormBuilder, Validators } from '@angular/forms';

interface Stock {
  value: string;
  viewValue: string;
}

interface TimeFrame {
  value: string;
  viewValue: string
}

@Component({
  selector: 'app-polygon-api-controller',
  templateUrl: './polygon-api-controller.component.html',
  styleUrls: ['./polygon-api-controller.component.scss']
  
})

@Injectable()
export class PolygonApiControllerComponent implements OnInit {
  selectedStock: Stock = {value:'',viewValue:''};
  stockForm = new FormGroup({
    selectedStockControl: new FormControl(this.selectedStock),
    selectedTimeFrameControl: new FormControl(),
    patternScore: new FormControl(),

  });
  loginForm = new FormGroup({
    email: new FormControl(),
    password: new FormControl(),
  });


  Constructor() {}
  @Output() selectedStockOutputter  = new EventEmitter<Stock | null>();
  @Output() selectedTimeFrameOutputter = new EventEmitter<TimeFrame | null>();
  @Input() patternScore = 0; //send harmonic patterns's accuracy score to sidebar to be displayed
  userName: string = 'Welcome to Stock Sorcerer'; //Welcome to Fibonacci Trader
  timeFrames: TimeFrame[] = [
    {value: 'daily', viewValue: 'Day'},
    {value: 'intraday', viewValue: 'Intraday'},
    {value: 'weekly', viewValue: 'Week'},
    {value: 'monthly', viewValue: 'Month'},
  ];

  stocks: Stock[] = [
    { value: 'AAPL', viewValue: 'Apple Inc.' },
    { value: 'MSFT', viewValue: 'Microsoft Corporation' },
    { value: 'GOOG', viewValue: 'Alphabet Inc. (GOOG)' },
    { value: 'GOOGL', viewValue: 'Alphabet Inc. (GOOGL)' },
    { value: 'AMZN', viewValue: 'Amazon.com, Inc.' },
    { value: 'NVDA', viewValue: 'NVIDIA Corporation' },
    { value: 'META', viewValue: 'Meta Platforms, Inc.' },
    { value: 'TSLA', viewValue: 'Tesla, Inc.' },
    { value: 'AVGO', viewValue: 'Broadcom Inc.' },
    { value: 'ADBE', viewValue: 'Adobe Inc.' },
    { value: 'ASML', viewValue: 'ASML Holding N.V.' },
    { value: 'COST', viewValue: 'Costco Wholesale Corporation' },
    { value: 'PEP', viewValue: 'PepsiCo, Inc.' },
    { value: 'CSCO', viewValue: 'Cisco Systems, Inc.' },
    { value: 'NFLX', viewValue: 'Netflix, Inc.' },
    { value: 'AZN', viewValue: 'AstraZeneca PLC' },
    { value: 'LIN', viewValue: 'Linde plc' },
    { value: 'AMD', viewValue: 'Advanced Micro Devices, Inc.' },
    { value: 'INTC', viewValue: 'Intel Corporation' },
    { value: 'CMCSA', viewValue: 'Comcast Corporation' },
    { value: 'TMUS', viewValue: 'T-Mobile US, Inc.' },
    { value: 'INTU', viewValue: 'Intuit Inc.' },
    { value: 'PDD', viewValue: 'PDD Holdings Inc.' },
    { value: 'AMGN', viewValue: 'Amgen Inc.' },
    { value: 'QCOM', viewValue: 'QUALCOMM Incorporated' },
    { value: 'TXN', viewValue: 'Texas Instruments Incorporated' },
    { value: 'AMAT', viewValue: 'Applied Materials, Inc.' },
    { value: 'HON', viewValue: 'Honeywell International Inc.' },
    { value: 'SBUX', viewValue: 'Starbucks Corporation' },
    { value: 'SNY', viewValue: 'Sanofi' },
    { value: 'BKNG', viewValue: 'Booking Holdings Inc.' },
    { value: 'ISRG', viewValue: 'Intuitive Surgical, Inc.' },
    { value: 'MDLZ', viewValue: 'Mondelez International, Inc.' },
    { value: 'ADP', viewValue: 'Automatic Data Processing, Inc.' },
    { value: 'GILD', viewValue: 'Gilead Sciences, Inc.' },
    { value: 'LRCX', viewValue: 'Lam Research Corporation' },
    { value: 'VRTX', viewValue: 'Vertex Pharmaceuticals Incorporated' },
    { value: 'ADI', viewValue: 'Analog Devices, Inc.' },
    { value: 'REGN', viewValue: 'Regeneron Pharmaceuticals, Inc.' },
    { value: 'MU', viewValue: 'Micron Technology, Inc.' },
    { value: 'ABNB', viewValue: 'Airbnb, Inc.' },
    { value: 'SNPS', viewValue: 'Synopsys, Inc.' },
    { value: 'PANW', viewValue: 'Palo Alto Networks, Inc.' },
    { value: 'CME', viewValue: 'CME Group Inc.' },
    { value: 'ATVI', viewValue: 'Activision Blizzard, Inc.' },
    { value: 'NTES', viewValue: 'NetEase, Inc.' },
    { value: 'KLAC', viewValue: 'KLA Corporation' },
    { value: 'EQIX', viewValue: 'Equinix, Inc.' },
    { value: 'MELI', viewValue: 'MercadoLibre, Inc.' },
    { value: 'CDNS', viewValue: 'Cadence Design Systems, Inc.' },
    { value: 'PYPL', viewValue: 'PayPal Holdings, Inc.' },
    { value: 'CHTR', viewValue: 'Charter Communications, Inc.' },
    { value: 'CSX', viewValue: 'CSX Corporation' },
    { value: 'WDAY', viewValue: 'Workday, Inc.' },
    { value: 'MAR', viewValue: 'Marriott International, Inc.' },
    { value: 'ORLY', viewValue: "O'Reilly Automotive, Inc." },
    { value: 'MNST', viewValue: 'Monster Beverage Corporation' },
    { value: 'ARM', viewValue: 'Arm Holdings Limited' },
    { value: 'CTAS', viewValue: 'Cintas Corporation' },
    { value: 'ROP', viewValue: 'Roper Technologies, Inc.' },
    { value: 'LULU', viewValue: 'Lululemon Athletica Inc.' },
    { value: 'NXPI', viewValue: 'NXP Semiconductors N.V.' },
    { value: 'MRVL', viewValue: 'Marvell Technology, Inc.' },
    { value: 'CRWD', viewValue: 'CrowdStrike Holdings, Inc.' },
    { value: 'TEAM', viewValue: 'Atlassian Corporation Plc' },
    { value: 'PCAR', viewValue: 'PACCAR Inc' },
    { value: 'CPRT', viewValue: 'Copart, Inc.' },
    { value: 'ADSK', viewValue: 'Autodesk, Inc.' },
    { value: 'JD', viewValue: 'JD.com, Inc.' },
    { value: 'MCHP', viewValue: 'Microchip Technology Incorporated' },
    { value: 'KDP', viewValue: 'Keurig Dr Pepper Inc.' },
    { value: 'ODFL', viewValue: 'Old Dominion Freight Line, Inc.' },
    { value: 'PAYX', viewValue: 'Paychex, Inc.' },
    { value: 'ROST', viewValue: 'Ross Stores, Inc.' },
    { value: 'KHC', viewValue: 'The Kraft Heinz Company' },
    { value: 'LI', viewValue: 'Li Auto Inc.' },
    { value: 'AEP', viewValue: 'American Electric Power Company, Inc.' },
    { value: 'FTNT', viewValue: 'Fortinet, Inc.' },
    { value: 'SGEN', viewValue: 'Seagen Inc.' },
    { value: 'EXC', viewValue: 'Exelon Corporation' },
    { value: 'BIDU', viewValue: 'Baidu, Inc.' },
    { value: 'CEG', viewValue: 'Constellation Energy Corporation' },
    { value: 'DXCM', viewValue: 'DexCom, Inc.' },
    { value: 'IDXX', viewValue: 'IDEXX Laboratories, Inc.' },
    { value: 'EA', viewValue: 'Electronic Arts Inc.' },
    { value: 'DDOG', viewValue: 'Datadog, Inc.' },
    { value: 'BKR', viewValue: 'Baker Hughes Company' },
    { value: 'VRSK', viewValue: 'Verisk Analytics, Inc.' },
    { value: 'FAST', viewValue: 'Fastenal Company' },
    { value: 'CTSH', viewValue: 'Cognizant Technology Solutions Corporation' },
    { value: 'CSGP', viewValue: 'CoStar Group, Inc.' },
    { value: 'IBKR', viewValue: 'Interactive Brokers Group, Inc.' },
    { value: 'TTD', viewValue: 'The Trade Desk, Inc.' },
    { value: 'BIIB', viewValue: 'Biogen Inc.' },
    { value: 'XEL', viewValue: 'Xcel Energy Inc.' },
    { value: 'MBLY', viewValue: 'Mobileye Global Inc.' },
    { value: 'GEHC', viewValue: 'GE HealthCare Technologies Inc.' },
    { value: 'GFS', viewValue: 'GLOBALFOUNDRIES Inc.' },
    { value: 'ACGL', viewValue: 'Arch Capital Group Ltd.' },
    { value: 'NDAQ', viewValue: 'Nasdaq, Inc.' },
    { value: 'ON', viewValue: 'ON Semiconductor Corporation' },
    { value: 'CDW', viewValue: 'CDW Corporation' },
    { value: 'MRNA', viewValue: 'Moderna, Inc.' },
    { value: 'ARGX', viewValue: 'argenx SE' },
    { value: 'CCEP', viewValue: 'Coca-Cola Europacific Partners PLC' },
    { value: 'MDB', viewValue: 'MongoDB, Inc.' },
    { value: 'FANG', viewValue: 'Diamondback Energy, Inc.' },
    { value: 'ZS', viewValue: 'Zscaler, Inc.' },
    { value: 'MPWR', viewValue: 'Monolithic Power Systems, Inc.' },
    { value: 'TTWO', viewValue: 'Take-Two Interactive Software, Inc.' },
    { value: 'DLTR', viewValue: 'Dollar Tree, Inc.' },
    { value: 'RYAAY', viewValue: 'Ryanair Holdings plc' },
    { value: 'ANSS', viewValue: 'ANSYS, Inc.' },
    { value: 'WBD', viewValue: 'Warner Bros. Discovery, Inc.' },
    { value: 'SPLK', viewValue: 'Splunk Inc.' },
    { value: 'SBAC', viewValue: 'SBA Communications Corporation' },
    { value: 'WTW', viewValue: 'Willis Towers Watson PLC' },
    { value: 'VOD', viewValue: 'Vodafone Group PLC' },
    { value: 'BNTX', viewValue: 'BioNTech SE' },
    { value: 'COIN', viewValue: 'Coinbase Global, Inc.' },
    { value: 'TCOM', viewValue: 'Trip.com Group Limited' },
    { value: 'TSCO', viewValue: 'Tractor Supply Company' },
    { value: 'ICLR', viewValue: 'ICON PLC' },
    { value: 'TROW', viewValue: 'T. Rowe Price Group, Inc.' },
    { value: 'FCNCA', viewValue: 'First Citizens BancShares, Inc.' },
    { value: 'EBAY', viewValue: 'eBay Inc.' },
    { value: 'ALNY', viewValue: 'Alnylam Pharmaceuticals, Inc.' },
    { value: 'TW', viewValue: 'Tradeweb Markets Inc.' },
    { value: 'LIFW', viewValue: 'MSP Recovery, Inc.' },
    { value: 'VRSN', viewValue: 'VeriSign, Inc.' },
    { value: 'SYM', viewValue: 'Symbotic Inc.' },
    { value: 'BGNE', viewValue: 'BeiGene, Ltd.' },
    { value: 'GMAB', viewValue: 'Genmab A/S' },
    { value: 'ULTA', viewValue: 'Ulta Beauty, Inc.' },
    { value: 'SIRI', viewValue: 'Sirius XM Holdings Inc.' },
    { value: 'ZM', viewValue: 'Zoom Video Communications, Inc.' },
    { value: 'JBHT', viewValue: 'J.B. Hunt Transport Services, Inc.' },
    { value: 'WBA', viewValue: 'Walgreens Boots Alliance, Inc.' },
    { value: 'FITB', viewValue: 'Fifth Third Bancorp' },
    { value: 'STLD', viewValue: 'Steel Dynamics, Inc.' },
    { value: 'PTC', viewValue: 'PTC Inc.' },
    { value: 'EXPE', viewValue: 'Expedia Group, Inc.' },
    { value: 'HOLX', viewValue: 'Hologic, Inc.' },
    { value: 'PFG', viewValue: 'Principal Financial Group, Inc.' },
    { value: 'DKNG', viewValue: 'DraftKings Inc.' },
    { value: 'AKAM', viewValue: 'Akamai Technologies, Inc.' },
    { value: 'WMG', viewValue: 'Warner Music Group Corp.' },
    { value: 'COO', viewValue: 'The Cooper Companies, Inc.' },
    { value: 'LPLA', viewValue: 'LPL Financial Holdings Inc.' },
    { value: 'AXON', viewValue: 'Axon Enterprise, Inc.' },
    { value: 'CHKP', viewValue: 'Check Point Software Technologies Ltd.' },
    { value: 'NTAP', viewValue: 'NetApp, Inc.' },
    { value: 'BMRN', viewValue: 'BioMarin Pharmaceutical Inc.' },
    { value: 'FSLR', viewValue: 'First Solar, Inc.' },
    { value: 'RPRX', viewValue: 'Royalty Pharma plc' },
    { value: 'ERIC', viewValue: 'Telefonaktiebolaget LM Ericsson (publ)' },
    { value: 'RIVN', viewValue: 'Rivian Automotive, Inc.' },
    { value: 'HBAN', viewValue: 'Huntington Bancshares Incorporated' },
    { value: 'CINF', viewValue: 'Cincinnati Financial Corporation' },
    { value: 'ILMN', viewValue: 'Illumina, Inc.' },
    { value: 'ALGN', viewValue: 'Align Technology, Inc.' },
    { value: 'BSY', viewValue: 'Bentley Systems, Incorporated' },
    { value: 'STX', viewValue: 'Seagate Technology Holdings plc' },
    { value: 'ntrs', viewValue: 'Northern Trust Corporation' },
    { value: 'entg', viewValue: 'Entegris, Inc.' },
    { value: 'smci', viewValue: 'Super Micro Computer, Inc.' },
    { value: 'swks', viewValue: 'Skyworks Solutions, Inc.' },
    { value: 'fwona', viewValue: 'Liberty Media Corp.' },
    { value: 'wdc', viewValue: 'Western Digital Corporation' },
    { value: 'erie', viewValue: 'Erie Indemnity Company' },
    { value: 'vfs', viewValue: 'VinFast Auto Ltd.' },
    { value: 'fox', viewValue: 'Fox Corporation' },
    { value: 'foxa', viewValue: 'Fox Corporation' },
    { value: 'ter', viewValue: 'Teradyne, Inc.' },
    { value: 'app', viewValue: 'AppLovin Corporation' },
    { value: 'ssnc', viewValue: 'SS&C Technologies Holdings, Inc.' },
    { value: 'manh', viewValue: 'Manhattan Associates, Inc.' },
    { value: 'pool', viewValue: 'Pool Corporation' },
    { value: 'logi', viewValue: 'Logitech International S.A.' },
    { value: 'ndsn', viewValue: 'Nordson Corporation' },
    { value: 'ual', viewValue: 'United Airlines Holdings, Inc.' },
    { value: 'roku', viewValue: 'Roku, Inc.' },
    { value: 'grab', viewValue: 'Grab Holdings Limited' },
    { value: 'xp', viewValue: 'XP Inc.' },
    { value: 'enph', viewValue: 'Enphase Energy, Inc.' },
    { value: 'gen', viewValue: 'Gen Digital Inc.' },
    { value: 'lnt', viewValue: 'Alliant Energy Corporation' },
    { value: 'lbrda', viewValue: 'Liberty Broadband Corporation' },
    { value: 'lbrdk', viewValue: 'Liberty Broadband Corporation' },
    { value: 'incy', viewValue: 'Incyte Corporation' },
    { value: 'lkq', viewValue: 'LKQ Corporation' },
    { value: 'glpi', viewValue: 'Gaming and Leisure Properties, Inc.' },
    { value: 'nws', viewValue: 'News Corporation' },
    { value: 'podd', viewValue: 'Insulet Corporation' },
    { value: 'hst', viewValue: 'Host Hotels & Resorts, Inc.' },
    { value: 'nwsa', viewValue: 'News Corporation' },
    { value: 'legn', viewValue: 'Legend Biotech Corporation' },
    { value: 'zi', viewValue: 'ZoomInfo Technologies Inc.' },
    { value: 'htht', viewValue: 'H World Group Limited' },
    { value: 'flex', viewValue: 'Flex Ltd.' },
    { value: 'okta', viewValue: 'Okta, Inc.' },
    { value: 'evrg', viewValue: 'Evergy, Inc.' },
    { value: 'azpn', viewValue: 'Aspen Technology, Inc.' },
    { value: 'morn', viewValue: 'Morningstar, Inc.' },
    { value: 'cg', viewValue: 'The Carlyle Group Inc.' },
    { value: 'apa', viewValue: 'APA Corporation' },
    { value: 'exas', viewValue: 'Exact Sciences Corporation' },
    { value: 'nice', viewValue: 'NICE Ltd.' },
    { value: 'reg', viewValue: 'Regency Centers Corporation' },
    { value: 'vtrs', viewValue: 'Viatris Inc.' },
    { value: 'arcc', viewValue: 'Ares Capital Corporation' },
    { value: 'jkhy', viewValue: 'Jack Henry & Associates, Inc.' },
    { value: 'leco', viewValue: 'Lincoln Electric Holdings, Inc.' },
    { value: 'zbra', viewValue: 'Zebra Technologies Corporation' },
    { value: 'saia', viewValue: 'Saia, Inc.' },
    { value: 'xm', viewValue: 'Qualtrics International Inc.' },
    { value: 'chk', viewValue: 'Chesapeake Energy Corporation' },
    { value: 'nbix', viewValue: 'Neurocrine Biosciences, Inc.' },
    { value: 'uthr', viewValue: 'United Therapeutics Corporation' },
    { value: 'trmb', viewValue: 'Trimble Inc.' },
    { value: 'tpg', viewValue: 'TPG Inc.' },
    { value: 'casy', viewValue: 'Casey\'s General Stores, Inc.' },
    { value: 'otex', viewValue: 'Open Text Corporation' },
    { value: 'five', viewValue: 'Five Below, Inc.' },
    { value: 'czr', viewValue: 'Caesars Entertainment, Inc.' },
    { value: 'wynn', viewValue: 'Wynn Resorts, Limited' },
    { value: 'lamr', viewValue: 'Lamar Advertising Company' },
    { value: 'ffiv', viewValue: 'F5, Inc.' },
    { value: 'dox', viewValue: 'Amdocs Limited' },
    { value: 'chrw', viewValue: 'C.H. Robinson Worldwide, Inc.' },
    { value: 'tech', viewValue: 'Bio-Techne Corporation' },
    { value: 'lcid', viewValue: 'Lucid Group, Inc.' },
    { value: 'ntnx', viewValue: 'Nutanix, Inc.' },
    { value: 'z', viewValue: 'Zillow Group, Inc.' },
    { value: 'dbx', viewValue: 'Dropbox, Inc.' },
    { value: 'zg', viewValue: 'Zillow Group, Inc.' },
    { value: 'qrvo', viewValue: 'Qorvo, Inc.' },
    { value: 'chdn', viewValue: 'Churchill Downs Incorporated' },
    { value: 'brkr', viewValue: 'Bruker Corporation' },
    { value: 'hsic', viewValue: 'Henry Schein, Inc.' },
    { value: 'etsy', viewValue: 'Etsy, Inc.' },
    { value: 'docu', viewValue: 'DocuSign, Inc.' },
    { value: 'paraa', viewValue: 'Paramount Global' },
    { value: 'ewbc', viewValue: 'East West Bancorp, Inc.' },
    { value: 'eslt', viewValue: 'Elbit Systems Ltd.' },
    { value: 'para', viewValue: 'Paramount Global' },
    { value: 'rgen', viewValue: 'Repligen Corporation' },
    {value: 'mtch', viewValue: 'Match Group, Inc.'},
    {value: 'futu', viewValue: 'Futu Holdings Limited'},
    {value: 'medp', viewValue: 'Medpace Holdings, Inc.'},
    {value: 'pcty', viewValue: 'Paylocity Holding Corporation'},
    {value: 'mktx', viewValue: 'MarketAxess Holdings Inc.'},
    {value: 'duol', viewValue: 'Duolingo, Inc.'},
    {value: 'ttek', viewValue: 'Tetra Tech, Inc.'},
    {value: 'lscc', viewValue: 'Lattice Semiconductor Corporation'},
    {value: 'mndy', viewValue: 'monday.com Ltd.'},
    {value: 'wwd', viewValue: 'Woodward, Inc.'},
    {value: 'aal', viewValue: 'American Airlines Group Inc.'},
    {value: 'iep', viewValue: 'Icahn Enterprises L.P.'},
    {value: 'jazz', viewValue: 'Jazz Pharmaceuticals plc'},
    {value: 'afrm', viewValue: 'Affirm Holdings, Inc.'},
    {value: 'srpt', viewValue: 'Sarepta Therapeutics, Inc.'},
    {value: 'lnw', viewValue: 'Light & Wonder, Inc.'},
    {value: 'cybr', viewValue: 'CyberArk Software Ltd.'},
    {value: 'oled', viewValue: 'Universal Display Corporation'},
    {value: 'seic', viewValue: 'SEI Investments Company'},
    {value: 'grfs', viewValue: 'Grifols, S.A.'},
    {value: 'hood', viewValue: 'Robinhood Markets, Inc.'},
    {value: 'wsc', viewValue: 'WillScot Mobile Mini Holdings Corp.'},
    {value: 'gtlb', viewValue: 'GitLab Inc.'},
    {value: 'bz', viewValue: 'Kanzhun Limited'},
    {value: 'txrh', viewValue: 'Texas Roadhouse, Inc.'},
    {value: 'nfe', viewValue: 'New Fortress Energy Inc.'},
    {value: 'mstr', viewValue: 'MicroStrategy Incorporated'},
    {value: 'rgld', viewValue: 'Royal Gold, Inc.'},
    {value: 'rmbs', viewValue: 'Rambus Inc.'},
    {value: 'cart', viewValue: 'Maplebear (Instacart) Inc.'},
    {value: 'cccs', viewValue: 'CCC Intelligent Solutions Holdings Inc.'},
    {value: 'gntx', viewValue: 'Gentex Corporation'},
    {value: 'appf', viewValue: 'AppFolio, Inc.'},
    {value: 'ions', viewValue: 'Ionis Pharmaceuticals, Inc.'},
    {value: 'roiv', viewValue: 'Roivant Sciences Ltd.'},
    {value: 'sofi', viewValue: 'SoFi Technologies, Inc.'},
    {value: 'car', viewValue: 'Avis Budget Group, Inc.'},
    {value: 'wfrd', viewValue: 'Weatherford International plc'},
    {value: 'achc', viewValue: 'Acadia Healthcare Company, Inc.'},
    {value: 'fsv', viewValue: 'FirstService Corporation'},
    {value: 'ufpi', viewValue: 'UFP Industries, Inc.'},
    {value: 'dsgx', viewValue: 'The Descartes Systems Group Inc.'},
    {value: 'yndx', viewValue: 'Yandex N.V.'},
    {value: 'mat', viewValue: 'Mattel, Inc.'},
    {value: 'exel', viewValue: 'Exelixis, Inc.'},
    {value: 'lbtya', viewValue: 'Liberty Global plc'},
    {value: 'lbtyk', viewValue: 'Liberty Global plc'},
    {value: 'chrd', viewValue: 'Chord Energy Corporation'},
    {value: 'midd', viewValue: 'The Middleby Corporation'},
    {value: 'wing', viewValue: 'Wingstop Inc.'},
    {value: 'has', viewValue: 'Hasbro, Inc.'},
    {value: 'krtx', viewValue: 'Karuna Therapeutics, Inc.'},
    {value: 'coke', viewValue: 'Coca-Cola Consolidated, Inc.'},
    {value: 'spsc', viewValue: 'SPS Commerce, Inc.'},
    {value: 'cgnx', viewValue: 'Cognex Corporation'},
    {value: 'qlys', viewValue: 'Qualys, Inc.'},
    {value: 'ntra', viewValue: 'Natera, Inc.'},
    {value: 'amkr', viewValue: 'Amkor Technology, Inc.'},
    {value: 'swav', viewValue: 'ShockWave Medical, Inc.'},
    {value: 'sivb', viewValue: 'SVB Financial Group'},
    {value: 'lstr', viewValue: 'Landstar System, Inc.'},
    {value: 'bili', viewValue: 'Bilibili Inc.'},
    {value: 'lbtyb', viewValue: 'Liberty Global plc'},
    {value: 'xray', viewValue: 'DENTSPLY SIRONA Inc.'},
    {value: 'ppc', viewValue: 'Pilgrim\'s Pride Corporation'},
    {value: 'cbsh', viewValue: 'Commerce Bancshares, Inc.'},
    {value: 'cflt', viewValue: 'Confluent, Inc.'},
    {value: 'sigi', viewValue: 'Selective Insurance Group, Inc.'},
    {value: 'altr', viewValue: 'Altair Engineering Inc.'},
    {value: 'lfus', viewValue: 'Littelfuse, Inc.'},
    {value: 'cnxc', viewValue: 'Concentrix Corporation'},
    {value: 'ensg', viewValue: 'The Ensign Group, Inc.'},
    {value: 'chx', viewValue: 'ChampionX Corporation'},
    {value: 'mtsi', viewValue: 'MACOM Technology Solutions Holdings, Inc.'},
    {value: 'hqy', viewValue: 'HealthEquity, Inc.'},
    {value: 'apls', viewValue: 'Apellis Pharmaceuticals, Inc.'},
    {value: 'ssb', viewValue: 'SouthState Corporation'},
    {value: 'cacc', viewValue: 'Credit Acceptance Corporation'},
    {value: 'reyn', viewValue: 'Reynolds Consumer Products Inc.'},
    {value: 'agnc', viewValue: 'AGNC Investment Corp.'},
    {value: 'nxt', viewValue: 'Nextracker Inc.'},
    {value: 'pnfp', viewValue: 'Pinnacle Financial Partners, Inc.'},
    { value: 'DOOO', viewValue: 'BRP Inc.' },
    { value: 'ALGM', viewValue: 'Allegro MicroSystems, Inc.' },
    { value: 'WIX', viewValue: 'Wix.com Ltd.' },
    { value: 'DLO', viewValue: 'DLocal Limited' },
    { value: 'ITCI', viewValue: 'Intra-Cellular Therapies, Inc.' },
    { value: 'DRS', viewValue: 'Leonardo DRS, Inc.' },
    { value: 'CROX', viewValue: 'Crocs, Inc.' },
    { value: 'FRSH', viewValue: 'Freshworks Inc.' },
    { value: 'ABCM', viewValue: 'Abcam plc' },
    { value: 'NSIT', viewValue: 'Insight Enterprises, Inc.' },
    { value: 'ZION', viewValue: 'Zions Bancorporation,NA' },
    { value: 'IQ', viewValue: 'iQIYI, Inc.' },
    { value: 'FYBR', viewValue: 'Frontier Communications Parent, Inc.' },
    { value: 'ASND', viewValue: 'Ascendis Pharma A/S' },
    { value: 'NXST', viewValue: 'Nexstar Media Group, Inc.' },
    { value: 'BPOP', viewValue: 'Popular, Inc.' },
    { value: 'OPCH', viewValue: 'Option Care Health, Inc.' },
    { value: 'AAON', viewValue: 'AAON, Inc.' },
    { value: 'HALO', viewValue: 'Halozyme Therapeutics, Inc.' },
    { value: 'WTFC', viewValue: 'Wintrust Financial Corporation' },
    { value: 'BBIO', viewValue: 'BridgeBio Pharma, Inc.' },
    { value: 'MKSI', viewValue: 'MKS Instruments, Inc.' },
    { value: 'NOVT', viewValue: 'Novanta Inc.' },
    { value: 'HLNE', viewValue: 'Hamilton Lane Incorporated' },
    { value: 'FCFS', viewValue: 'FirstCash Holdings, Inc' },
    { value: 'FIVN', viewValue: 'Five9, Inc.' },
    { value: 'BECN', viewValue: 'Beacon Roofing Supply, Inc.' },
    { value: 'OLLI', viewValue: 'Ollie\'s Bargain Outlet Holdings, Inc.' },
    { value: 'FRHC', viewValue: 'Freedom Holding Corp.' },
    { value: 'PTEN', viewValue: 'Patterson-UTI Energy, Inc.' },
    { value: 'IMVT', viewValue: 'Immunovant, Inc.' },
    { value: 'BRZE', viewValue: 'Braze, Inc.' },
    { value: 'BOKF', viewValue: 'BOK Financial Corporation' },
    { value: 'VNOM', viewValue: 'Viper Energy Partners LP' },
    { value: 'MASI', viewValue: 'Masimo Corporation' },
    { value: 'CIGI', viewValue: 'Colliers International Group Inc.' },
    { value: 'TXG', viewValue: '10x Genomics, Inc.' },
    { value: 'COLB', viewValue: 'Columbia Banking System, Inc.' },
    { value: 'PCVX', viewValue: 'Vaxcyte, Inc.' },
    { value: 'COLM', viewValue: 'Columbia Sportswear Company' },
    { value: 'GLBE', viewValue: 'Global-e Online Ltd.' },
    { value: 'PSNY', viewValue: 'Polestar Automotive Holding UK PLC' },
    { value: 'LNTH', viewValue: 'Lantheus Holdings, Inc.' },
    { value: 'LANC', viewValue: 'Lancaster Colony Corporation' },
    { value: 'OZK', viewValue: 'Bank OZK' },
    { value: 'CWST', viewValue: 'Casella Waste Systems, Inc.' },
    { value: 'PECO', viewValue: 'Phillips Edison & Company, Inc.' },
    { value: 'IRDM', viewValue: 'Iridium Communications Inc.' },
    { value: 'TENB', viewValue: 'Tenable Holdings, Inc.' },
    { value: 'EXLS', viewValue: 'ExlService Holdings, Inc.' },
    { value: 'SEDG', viewValue: 'SolarEdge Technologies, Inc.' },
    { value: 'IPGP', viewValue: 'IPG Photonics Corporation' },
    { value: 'GGAL', viewValue: 'Grupo Financiero Galicia S.A.' },
    { value: 'FIZZ', viewValue: 'National Beverage Corp.' },
    { value: 'MMYT', viewValue: 'MakeMyTrip Limited' },
    { value: 'ACLS', viewValue: 'Axcelis Technologies, Inc.' },
    { value: 'VLY', viewValue: 'Valley National Bancorp' },
    { value: 'UBSI', viewValue: 'United Bankshares, Inc.' },
    { value: 'RCM', viewValue: 'R1 RCM Inc.' },
    { value: 'POWI', viewValue: 'Power Integrations, Inc.' },
    { value: 'ACT', viewValue: 'Enact Holdings, Inc.' },
    { value: 'CRSP', viewValue: 'CRISPR Therapeutics AG' },
    { value: 'TWNK', viewValue: 'Hostess Brands, Inc.' },
    { value: 'SBNY', viewValue: 'Signature Bank' },
    { value: 'AVT', viewValue: 'Avnet, Inc.' },
    { value: 'ONB', viewValue: 'Old National Bancorp' },
    { value: 'CERE', viewValue: 'Cerevel Therapeutics Holdings, Inc.' },
    { value: 'SFM', viewValue: 'Sprouts Farmers Market, Inc.' },
    { value: 'FTAI', viewValue: 'FTAI Aviation Ltd' },
    { value: 'STNE', viewValue: 'StoneCo Ltd.' },
    { value: 'QDEL', viewValue: 'QuidelOrtho Corporation' },
    { value: 'IAC', viewValue: 'IAC Inc.' },
    { value: 'SRCL', viewValue: 'Stericycle, Inc.' },
    { value: 'MMSI', viewValue: 'Merit Medical Systems, Inc.' },
    { value: 'IMGN', viewValue: 'ImmunoGen, Inc.' },
    { value: 'EEFT', viewValue: 'Euronet Worldwide, Inc.' },
    { value: 'ESGR', viewValue: 'Enstar Group Limited' },
    { value: 'CRUS', viewValue: 'Cirrus Logic, Inc.' },
    { value: 'LOPE', viewValue: 'Grand Canyon Education, Inc'},
    { value: 'ipar', viewValue: 'Inter Parfums, Inc.' },
    { value: 'vrns', viewValue: 'Varonis Systems, Inc.' },
    { value: 'fele', viewValue: 'Franklin Electric Co., Inc.' },
    { value: 'rely', viewValue: 'Remitly Global, Inc.' },
    { value: 'lyft', viewValue: 'Lyft, Inc.' },
    { value: 'syna', viewValue: 'Synaptics Incorporated' },
    { value: 'hcp', viewValue: 'HashiCorp, Inc.' },
    { value: 'pega', viewValue: 'Pegasystems Inc.' },
    { value: 'bcpc', viewValue: 'Balchem Corporation' },
    { value: 'verx', viewValue: 'Vertex, Inc.' },
    { value: 'gt', viewValue: 'The Goodyear Tire & Rubber Company' },
    { value: 'celh', viewValue: 'Celsius Holdings, Inc.' },
    { value: 'alks', viewValue: 'Alkermes plc' },
    { value: 'blkb', viewValue: 'Blackbaud, Inc.' },
    { value: 'mrtx', viewValue: 'Mirati Therapeutics, Inc.' },
    { value: 'sgry', viewValue: 'Surgery Partners, Inc.' },
    { value: 'expo', viewValue: 'Exponent, Inc.' },
    { value: 'wen', viewValue: 'The Wendy\'s Company' },
    { value: 'shc', viewValue: 'Sotera Health Company' },
    { value: 'bpmc', viewValue: 'Blueprint Medicines Corporation' },
    { value: 'smpl', viewValue: 'The Simply Good Foods Company' },
    { value: 'pagp', viewValue: 'Plains GP Holdings, L.P.' },
    { value: 'ffin', viewValue: 'First Financial Bankshares, Inc.' },
    { value: 'tfsl', viewValue: 'TFS Financial Corporation' },
    { value: 'coop', viewValue: 'Mr. Cooper Group Inc.' },
    { value: 'pch', viewValue: 'PotlatchDeltic Corporation' },
    { value: 'acad', viewValue: 'ACADIA Pharmaceuticals Inc.' },
    { value: 'nuvl', viewValue: 'Nuvalent, Inc.' },
    { value: 'penn', viewValue: 'PENN Entertainment, Inc.' },
    { value: 'aso', viewValue: 'Academy Sports and Outdoors, Inc.' },
    { value: 'pycr', viewValue: 'Paycor HCM, Inc.' },
    { value: 'crvl', viewValue: 'CorVel Corporation' },
    { value: 'umbf', viewValue: 'UMB Financial Corporation' },
    { value: 'aeis', viewValue: 'Advanced Energy Industries, Inc.' },
    { value: 'hwc', viewValue: 'Hancock Whitney Corporation' },
    { value: 'insm', viewValue: 'Insmed Incorporated' },
    { value: 'evo', viewValue: 'Evotec SE' },
    { value: 'nari', viewValue: 'Inari Medical, Inc.' },
    { value: 'neog', viewValue: 'Neogen Corporation' },
    { value: 'nvmi', viewValue: 'Nova Ltd.' },
    { value: 'flnc', viewValue: 'Fluence Energy, Inc.' },
    { value: 'bl', viewValue: 'BlackLine, Inc.' },
    { value: 'verrm', viewValue: 'Verra Mobility Corporation' },
    { value: 'omab', viewValue: 'Grupo Aeroportuario del Centro Norte, SAB de CV' },
    { value: 'slm', viewValue: 'SLM Corporation' },
    { value: 'vc', viewValue: 'Visteon Corporation' },
    { value: 'ncno', viewValue: 'nCino, Inc.' },
    { value: 'avav', viewValue: 'AeroVironment, Inc.' },
    { value: 'cd', viewValue: 'Chindata Group Holdings Limited' },
    { value: 'urbn', viewValue: 'Urban Outfitters, Inc.' },
    { value: 'sbra', viewValue: 'Sabra Health Care REIT, Inc.' },
    { value: 'frpt', viewValue: 'Freshpet, Inc.' },
    { value: 'ottr', viewValue: 'Otter Tail Corporation' },
    { value: 'slab', viewValue: 'Silicon Laboratories Inc.' },
    { value: 'hcm', viewValue: 'HUTCHMED (China) Limited' },
    { value: 'rusha', viewValue: 'Rush Enterprises, Inc.' },
    { value: 'ccoi', viewValue: 'Cogent Communications Holdings, Inc.' },
    { value: 'rushb', viewValue: 'Rush Enterprises, Inc.' },
    { value: 'bhf', viewValue: 'Brighthouse Financial, Inc.' },
    { value: 'bgc', viewValue: 'BGC Group, Inc' },
    { value: 'diod', viewValue: 'Diodes Incorporated' },
    { value: 'mlco', viewValue: 'Melco Resorts & Entertainment Limited' },
    { value: 'olk', viewValue: 'Olink Holding AB (publ)' },
    { value: 'azta', viewValue: 'Azenta, Inc.' },
    { value: 'mq', viewValue: 'Marqeta, Inc.' },
    { value: 'mdgl', viewValue: 'Madrigal Pharmaceuticals, Inc.' },
    { value: 'rare', viewValue: 'Ultragenyx Pharmaceutical Inc.' },
    { value: 'aur', viewValue: 'Aurora Innovation, Inc.' },
    { value: 'rpd', viewValue: 'Rapid7, Inc.' },
    { value: 'nwl', viewValue: 'Newell Brands Inc.' },
    { value: 'wire', viewValue: 'Encore Wire Corporation' },
    { value: 'cytk', viewValue: 'Cytokinetics, Incorporated' },
    { value: 'spt', viewValue: 'Sprout Social, Inc.' },
    { value: 'cvlt', viewValue: 'Commvault Systems, Inc.' },
    { value: 'pgny', viewValue: 'Progyny, Inc.' },
    { value: 'jjsf', viewValue: 'J&J Snack Foods Corp.' },
    { value: 'nwe', viewValue: 'NorthWestern Corporation' },
    { value: 'fold', viewValue: 'Amicus Therapeutics, Inc.' },
    { value: 'iart', viewValue: 'Integra LifeSciences Holdings Corporation' },
    { value: 'zd', viewValue: 'Ziff Davis, Inc.' },
    { value: 'AMED', viewValue: 'Amedisys, Inc.' },
  { value: 'SRAD', viewValue: 'Sportradar Group AG' },
  { value: 'PDCO', viewValue: 'Patterson Companies, Inc.' },
  { value: 'WDFC', viewValue: 'WD-40 Company' },
  { value: 'MEOH', viewValue: 'Methanex Corporation' },
  { value: 'LITE', viewValue: 'Lumentum Holdings Inc.' },
  { value: 'STEP', viewValue: 'StepStone Group Inc.' },
  { value: 'ITRI', viewValue: 'Itron, Inc.' },
  { value: 'ABCB', viewValue: 'Ameris Bancorp' },
  { value: 'TSEM', viewValue: 'Tower Semiconductor Ltd.' },
  { value: 'FORM', viewValue: 'FormFactor, Inc.' },
  { value: 'UCBI', viewValue: 'United Community Banks, Inc.' },
  { value: 'PLTK', viewValue: 'Playtika Holding Corp.' },
  { value: 'SGML', viewValue: 'Sigma Lithium Corporation' },
  { value: 'VIRT', viewValue: 'Virtu Financial, Inc.' },
  { value: 'YY', viewValue: 'JOYY Inc.' },
  { value: 'AAWW', viewValue: 'Atlas Air Worldwide Holdings, Inc.' },
  { value: 'PLXS', viewValue: 'Plexus Corp.' },
  { value: 'GO', viewValue: 'Grocery Outlet Holding Corp.' },
  { value: 'ALRM', viewValue: 'Alarm.com Holdings, Inc.' },
  { value: 'IBOC', viewValue: 'International Bancshares Corporation' },
  { value: 'ARCB', viewValue: 'ArcBest Corporation' },
  { value: 'FTRE', viewValue: 'Fortrea Holdings Inc.' },
  { value: 'LGIH', viewValue: 'LGI Homes, Inc.' },
  { value: 'AXNX', viewValue: 'Axonics, Inc.' },
  { value: 'ARWR', viewValue: 'Arrowhead Pharmaceuticals, Inc.' },
  { value: 'TIGO', viewValue: 'Millicom International Cellular S.A.' },
  { value: 'BANF', viewValue: 'BancFirst Corporation' },
  { value: 'WB', viewValue: 'Weibo Corporation' },
  { value: 'FROG', viewValue: 'JFrog Ltd.' },
  { value: 'SANM', viewValue: 'Sanmina Corporation' },
  { value: 'AXSM', viewValue: 'Axsome Therapeutics, Inc.' },
  { value: 'APPN', viewValue: 'Appian Corporation' },
  { value: 'ACIW', viewValue: 'ACI Worldwide, Inc.' },
  { value: 'ARLP', viewValue: 'Alliance Resource Partners, L.P.' },
  { value: 'AMPH', viewValue: 'Amphastar Pharmaceuticals, Inc.' },
  { value: 'BMBL', viewValue: 'Bumble Inc.' },
  { value: 'INDV', viewValue: 'Indivior PLC' },
  { value: 'KRYS', viewValue: 'Krystal Biotech, Inc.' },
  { value: 'NVEI', viewValue: 'Nuvei Corporation' },
  { value: 'CAMT', viewValue: 'Camtek Ltd.' },
  { value: 'PRVA', viewValue: 'Privia Health Group, Inc.' },
  { value: 'SHOO', viewValue: 'Steven Madden, Ltd.' },
  { value: 'FTDR', viewValue: 'Frontdoor, Inc.' },
  { value: 'ZLAB', viewValue: 'Zai Lab Limited' },
  { value: 'GSHD', viewValue: 'Goosehead Insurance, Inc' },
  { value: 'IBRX', viewValue: 'ImmunityBio, Inc.' },
  { value: 'CATY', viewValue: 'Cathay General Bancorp' },
  { value: 'TCBI', viewValue: 'Texas Capital Bancshares, Inc.' },
  { value: 'IOSP', viewValue: 'Innospec Inc.' },
  { value: 'CSWI', viewValue: 'CSW Industrials, Inc.' },
  { value: 'HTZ', viewValue: 'Hertz Global Holdings, Inc.' },
  { value: 'FIBK', viewValue: 'First Interstate BancSystem, Inc.' },
  { value: 'MGEE', viewValue: 'MGE Energy, Inc.' },
  { value: 'INTA', viewValue: 'Intapp, Inc.' },
  { value: 'GH', viewValue: 'Guardant Health, Inc.' },
  { value: 'FLYW', viewValue: 'Flywire Corporation' },
  { value: 'TRMD', viewValue: 'TORM plc' },
  { value: 'SHLS', viewValue: 'Shoals Technologies Group, Inc.' },
  { value: 'QFIN', viewValue: 'Qifu Technology Inc.' },
  { value: 'KLIC', viewValue: 'Kulicke and Soffa Industries, Inc.' },
  { value: 'TRIP', viewValue: 'Tripadvisor, Inc.' },
  { value: 'FOXF', viewValue: 'Fox Factory Holding Corp.' },
  { value: 'PLUG', viewValue: 'Plug Power Inc.' },
  { value: 'CORT', viewValue: 'Corcept Therapeutics Incorporated' },
  { value: 'CRDO', viewValue: 'Credo Technology Group Holding Ltd' },
  { value: 'RRR', viewValue: 'Red Rock Resorts, Inc.' },
  { value: 'SITM', viewValue: 'SiTime Corporation' },
  { value: 'LIVN', viewValue: 'LivaNova PLC' },
  { value: 'CVBF', viewValue: 'CVB Financial Corp.' },
  { value: 'ATAT', viewValue: 'Atour Lifestyle Holdings Limited' },
  { value: 'DNLI', viewValue: 'Denali Therapeutics Inc.' },
  { value: 'ACVA', viewValue: 'ACV Auctions Inc.' },
  { value: 'GBDC', viewValue: 'Golub Capital BDC, Inc.' },
  { value: 'RUN', viewValue: 'Sunrun Inc.' },
  { value: 'DCT', viewValue: 'Duck Creek Technologies, Inc.' },
  { value: 'MGRC', viewValue: 'McGrath RentCorp' },
  { value: 'WERN', viewValue: 'Werner Enterprises, Inc.' },
  { value: 'IRTC', viewValue: 'iRhythm Technologies, Inc.' },
  { value: 'INDB', viewValue: 'Independent Bank Corp.' },
  ];
  //selectedStock: string = "IBM";
  selectedStocks: Array<Stock> = this.stocks;
  defaultStock: Stock =  this.stocks[1];
  
  onKey(value: string) { //Receive user input and send to search method
    this.selectedStocks = this.search(value);
  }

  search(value: string) {
    console.log('value = ' + value);
    const filter = value.toLowerCase();
    return this.stocks
      .filter(option => option.viewValue.toLowerCase().includes(filter) || option.value.toLowerCase().includes(filter))
      .sort((a, b) => {
        const aStartsWith = a.viewValue.toLowerCase().startsWith(filter) || a.value.toLowerCase().startsWith(filter);
        const bStartsWith = b.viewValue.toLowerCase().startsWith(filter) || b.value.toLowerCase().startsWith(filter);
        if (aStartsWith && !bStartsWith) {
          return -1;
        } else if (!aStartsWith && bStartsWith) {
          return 1;
        } else {
          return 0;
        }
      });
  }

  displayStock(stock?: Stock): string {
    return stock ? stock.viewValue : '';
  }

  highlightText(event: FocusEvent) {
    const inputElement = event.target as HTMLInputElement;
    inputElement.select();
  }
  

  /*search(value: string) { // Filter the stocks list and send back to populate the selectedStates**
    console.log('value = '+ value)
    let filter = value.toLowerCase();
    return this.stocks.filter(option => option.viewValue.toLowerCase().includes(filter));
  }*/
    
  changeStock(event: Event) {
    this.selectedStockOutputter.emit(this.stockForm.controls['selectedStockControl'].value);
  }

  changeTimeFrame(event: Event) {
    this.selectedTimeFrameOutputter.emit(this.stockForm.controls['selectedTimeFrameControl'].value);
  }

  ngOnInit(): void {
    this.stockForm.controls['selectedStockControl'].setValue(this.stocks[0]);
    this.stockForm.controls['selectedTimeFrameControl'].setValue(this.timeFrames[0]);
  }
  //cool = fetch(https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/day/2023-01-09/2023-01-09?apiKey=DyjKi8UpFyFhpIgQ1krDJycMOkW5nGs9);
}